AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template - S3 Bucket and EC2 Instance in Singapore (ap-southeast-1)

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair for SSH access
    Type: AWS::EC2::KeyPair::KeyName

Resources:

  # S3 Bucket
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: varshicfjenkins   # Static, globally unique name
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Purpose
          Value: Demo-S3

  # Security Group
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: EC2-SG

  # EC2 Instance
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-03c7d01cf1b3b8cbf  # Amazon Linux 2 AMI for ap-southeast-1
      SecurityGroups:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: varshi-cf

Outputs:
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref MyS3Bucket

  InstancePublicIp:
    Description: Public IP of EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp

  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MyEC2Instance
